/**
 * The construct map — X++ and the D365FO stack broken down one level BELOW the
 * artifact taxonomy, as a list of named constructs per axis.
 *
 * Why this exists. `eval/COVERAGE.md` answers "is there a knowledge entry, a
 * captured golden and a write path for *SSRS report*?" — one leaf per artifact
 * kind. That is the right granularity for a closure queue and the wrong one for
 * the question a developer actually asks a copilot ("does it know that a TempDB
 * temp table in a non-pre-processed DP must be bound to the report's user
 * connection?"). Coverage read 100% while 147 of 266 reporting constructs and 120
 * of 178 testing constructs had no line anywhere in the knowledge base.
 *
 * So: enumerate the constructs, match them against the sources, and let the zeros
 * be the gap list. `termProbe.ts` does the matching; this file is the vocabulary.
 *
 * HOW TO READ A ZERO. A zero is a *candidate* gap, never a verdict. Three ways it
 * lies, all of them paid for:
 *  1. The term names something the sources spell differently. This is why
 *     function terms here are BARE NAMES (`abs`, not `abs(`) — the first run of
 *     this probe reported ten predefined functions as missing because
 *     `compilerFacts.generated.ts` stores them as `abs: { min: 1, max: 1 }` and
 *     the term carried a paren.
 *  2. The construct is covered by a mechanism rather than by prose — FN001 checks
 *     170 function arities from a captured table; no entry needs to name them.
 *  3. The term is a generic word. Those are kept on purpose (see `weight`), so
 *     that a zero on a rare word is unambiguous rather than absent.
 *
 * HOW TO ADD. One entry per construct a developer can write, at the granularity
 * they would ask about. Add the regex only when the plain name would be ambiguous
 * or is not a word (`@"`, `[n,m]`); otherwise leave it out and the probe matches
 * the name as a whole word, case-insensitively.
 */

export interface Term {
  /** The construct, as a developer would name it. */
  name: string;
  /** Override for names that are not plain words. Matched case-insensitively. */
  re?: RegExp;
  /**
   * `core` = a construct met in ordinary project work; `exotic` = real but rare.
   * The probe reports them separately, so a gap list can be triaged without
   * re-reading every row.
   */
  weight?: 'core' | 'exotic';
}

export interface Axis {
  id: string;
  title: string;
  terms: Term[];
}

const t = (name: string, re?: RegExp, weight?: Term['weight']): Term => ({ name, re, weight });
const x = (name: string, re?: RegExp): Term => ({ name, re, weight: 'exotic' });

export const AXES: Axis[] = [
  {
    id: 'A',
    title: 'Lexical structure & literals',
    terms: [
      t('verbatim string'),
      t('@"', /@"/),
      t("@'", /@'/),
      t('escape sequence'),
      t('hex literal'),
      t('0x', /\b0x[0-9a-f]+/i),
      t('int64 literal'),
      t('utcdatetime literal'),
      t('date literal', /\b\d{1,2}\\\d{1,2}\\\d{4}\b|\bdate literal\b/),
      t('timeOfDay'),
      t('guid literal'),
      t('doc comment'),
      t('///', /\/\/\//),
      t('breakpoint'),
      t('print statement'),
      x('pause'),
      x('window'),
    ],
  },
  {
    id: 'B',
    title: 'Types & declarations',
    terms: [
      t('anytype'), t('boolean'), t('int64'), t('real'), t('guid'), t('utcdatetime'),
      t('container'), t('enum'), t('str'),
      t('str n', /\bstr\s+\d+\b|\bstr n\b/),
      t('var'), t('const'), t('readonly'),
      t('static field'),
      t('array'),
      t('dynamic array', /\[\s*\]\s*;|\bdynamic array\b/),
      t('array in memory', /\[\s*\d+\s*,\s*\d+\s*\]|\barray in memory\b'/),
      t('null'), t('default value'), t('optional parameter'),
      t('anytype parameter'),
      t('byref'),
      t('implicit conversion'),
      t('any2Str'), t('any2Int'), t('typeOf'),
      x('SysDictType'),
    ],
  },
  {
    id: 'C',
    title: 'Operators',
    terms: [
      t('like'),
      t('is operator', /\bis operator\b|\bis\b/),
      t('as operator', /\bas operator\b|\bas\b/),
      t('mod'), t('div'),
      t('ternary', /\bternary\b|\?\s*[^:\s][^:]{0,40}:/),
      t('bitwise'),
      t('<<', /<</), t('>>', />>/),
      t('xor', /\bxor\b|\^/),
      t('bitwise not', /\bbitwise not\b|~/),
      t('operator precedence'),
      t('+=', /\+=/), t('*=', /\*=/), t('++', /\+\+/),
      t('string concatenation'),
      t('container +=', /container \+=/),
      t('container destructuring', /\[\s*\w+\s*,\s*\w+\s*\]\s*=|\bcontainer destructuring\b/),
      t('conIns'), t('conPeek'), t('conDel'), t('conLen'), t('conFind'), t('conNull'), t('conPoke'),
    ],
  },
  {
    id: 'D',
    title: 'Statements & flow',
    terms: [
      t('switch'), t('fallthrough'), t('default:', /default:/),
      t('do while'), t('break'), t('continue'),
      t('try'), t('catch'), t('finally'), t('retry'), t('throw'),
      t('using statement'),
      t('ttsbegin'), t('ttscommit'), t('ttsabort'), t('ttsLevel'),
      t('changecompany'), t('unchecked'), t('Uncheck::', /Uncheck::/), t('flush'),
      t('Exception::', /Exception::/),
      t('Exception::CLRError', /Exception::CLRError/),
      t('Exception::UpdateConflict', /Exception::UpdateConflict/),
      t('Exception::Deadlock', /Exception::Deadlock/),
      t('Exception::DuplicateKeyException', /Exception::DuplicateKeyException/),
      t('UpdateConflictNotRecovered'),
      t('currentRetryCount'),
      t('checkFailed'), t('setPrefix'), t('infolog'), t('infologLine'),
      x('SysInfoAction'),
      t('Global::error', /Global::error/),
    ],
  },
  {
    id: 'E',
    title: 'Data statements (select, set-based, query object model)',
    terms: [
      t('select'), t('while select'),
      t('firstOnly'), t('firstOnly10'), t('firstFast'), t('forUpdate'), t('noFetch'), t('reverse'),
      t('optimisticLock'), t('pessimisticLock'), t('repeatableRead'),
      t('crossCompany'), t('validTimeState'), t('generateOnly'),
      t('forceLiterals'), t('forcePlaceholders'), t('forceNestedLoop'), t('forceSelectOrder'),
      t('index hint'), t('order by'), t('group by'),
      t('sum'), t('avg'), t('minof'), t('maxof'), t('count'),
      t('outer join'), t('exists join'), t('notexists join'),
      t('insert_recordset'), t('update_recordset'), t('delete_from'), t('setting'),
      t('skipDataMethods'), t('skipDeleteActions'), t('skipDatabaseLog'), t('skipEvents'),
      t('skipAosValidation'),
      t('RecordInsertList'), t('RecordSortedList'),
      t('doInsert'), t('doUpdate'), t('doDelete'),
      t('selectForUpdate'), t('reread'), t('orig'), t('RecVersion'),
      t('buf2Buf'), t('data method', /\bdata\(\)|\bdata method\b/), t('merge'),
      t('setTmp'), t('setTmpData'), t('setConnection'), t('wasCached'),
      t('isFieldDataRetrieved'), t('fieldState'),
      t('dynamic field syntax', /\.\(\s*\w+\s*\)|\bdynamic field\b/),
      t('fieldName2Id'), t('fieldId2Name'),
      t('select expression'), t('getSQLStatements'),
      t('SysDa'), t('SysDaQueryObject'), t('SysDaUpdateObject'),
      t('Query'), t('QueryRun'), t('QueryBuildDataSource'), t('QueryBuildRange'), t('QueryFilter'),
      t('SysQuery::value', /SysQuery::value/), t('SysQuery::range', /SysQuery::range/),
      t('SysQueryRangeUtil'), t('QueryRangeFunction'), t('addLink'), t('JoinMode'),
      t('QueryFetchMode'),
      t('MultiSelectionHelper'),
      t('UnitOfWork'), t('update conflict'),
    ],
  },
  {
    id: 'F',
    title: 'Macros & preprocessor',
    terms: [
      t('#define', /#define/), t('#localmacro', /#localmacro/), t('#endmacro', /#endmacro/),
      t('#macrolib', /#macrolib/), t('#if', /#if\b/), t('#ifnot', /#ifnot/), t('#endif', /#endif/),
      t('#undef', /#undef/),
      x('#globaldefine', /#globaldefine/), x('#globalmacro', /#globalmacro/),
      x('#linenumber', /#linenumber/), x('#defInc', /#defInc/), x('#defDec', /#defDec/),
      t('macro parameter', /%1|\bmacro parameter\b/),
      t('#CurrentVersion', /#CurrentVersion/), t('#CurrentList', /#CurrentList/),
      x('#AOT', /#AOT\b/), x('#Properties', /#Properties/), x('#Task', /#Task\b/),
      x('#resAppl', /#resAppl/), x('#File', /#File\b/),
    ],
  },
  {
    id: 'G',
    title: 'Functions (intrinsic & predefined)',
    // Bare names on purpose — see the header. These are checked against the
    // captured compiler tables, not against prose.
    terms: [
      t('strFmt'), t('strLen'), t('subStr'), t('strScan'), t('strUpr'), t('strLwr'), t('strRem'),
      t('strReplace'), t('strAlpha'), t('strDel'), t('strIns'), t('strPoke'), t('strLTrim'),
      t('strRTrim'), t('strSplit'), t('strStartsWith'), t('strEndsWith'), t('strContains'),
      t('num2Char'), t('char2Num'), t('strFind'), t('strNFind'), t('strLine'), t('strCmp'),
      t('strKeep'), t('strRep'), t('match'),
      t('num2Str'), t('str2Num'), t('int2Str'), t('str2Int'), t('str2Int64'), t('real2Int'),
      t('enum2Str'), t('str2Enum'), t('enum2Symbol'), t('symbol2Enum'), t('enum2Value'),
      t('str2Date'), t('date2Str'), t('str2Datetime'), t('datetime2Str'), t('date2Num'),
      t('mkDate'), t('dayOfMth'), t('mthOfYr'), t('prevMth'), t('nextMth'), t('endMth'),
      t('today'), t('systemDateGet'), t('dateNull'), t('timeNow'), t('DateTimeUtil'),
      t('abs'), t('round'), t('decRound'), t('power'), t('frac'), t('trunc'),
      t('newGuid'), t('guid2Str'), t('str2Guid'),
      t('curUserId'), t('curExt'), t('funcName'), t('sessionId'), t('getPrefix'), t('runAs'),
      t('classIdGet'), t('tableName2Id'), t('tableId2Name'), t('tableId2PName'), t('className2Id'),
      t('prmIsDefault'), t('sleep'), t('conPoke2', /\bcon2Str\b/),
      // Intrinsics.
      t('classNum'), t('classStr'), t('tableNum'), t('tableStr'), t('fieldNum'), t('fieldStr'),
      t('fieldPName'), t('methodStr'), t('staticMethodStr'), t('tableMethodStr'),
      t('tableStaticMethodStr'), t('enumNum'), t('enumStr'), t('enumLiteralStr'), t('enumCnt'),
      t('extendedTypeNum'), t('extendedTypeStr'),
      t('menuItemDisplayStr'), t('menuItemActionStr'), t('menuItemOutputStr'), t('menuStr'),
      t('formStr'), t('formControlStr'), t('formDataSourceStr'), t('formDataFieldStr'),
      t('formMethodStr'), t('queryStr'), t('queryDatasourceStr'), t('queryMethodStr'),
      t('reportStr'), t('ssrsReportStr'), t('resourceStr'), t('identifierStr'), t('literalStr'),
      t('delegateStr'), t('staticDelegateStr'), t('attributeStr'), t('tableFieldGroupStr'),
      t('indexStr'), t('indexNum'), t('varStr'), t('tablePName'),
      t('configurationKeyStr'), t('configurationKeyNum'),
      t('licenseCodeStr'), t('licenseCodeNum'),
      t('dataEntityDataSourceStr'), t('dataEntityViewStr'), t('tableCollectionStr'),
      t('privilegeStr'), t('dutyStr'), t('roleStr'), t('tileStr'), t('mapStr'), t('viewStr'),
      t('workflowTypeStr'), t('workflowTaskStr'), t('workflowApprovalStr'), t('workflowCategoryStr'),
      t('measureStr'), t('measurementStr'),
      x('dimensionHierarchyStr'), x('dimensionHierarchyLevelStr'), x('dimensionReferenceStr'),
      x('webActionItemStr'), x('maxDate'), x('maxInt'), x('minInt'),
    ],
  },
  {
    id: 'H',
    title: 'Classes, OOP & the extension model',
    terms: [
      t('extends'), t('implements'), t('interface'), t('abstract'), t('final'), t('static'),
      t('internal'), t('protected internal'), t('finalize'), t('super'),
      t('static constructor'), t('construct pattern'), t('static main'),
      t('newParameters'), t('parm method'), t('singleton'),
      t('delegate'), t('eventhandler'), t('SubscribesTo'),
      t('PreHandlerFor'), t('PostHandlerFor'), t('XppPrePostArgs'),
      t('ExtensionOf'), t('Hookable'), t('Wrappable'), t('Replaceable'), t('SysObsolete'),
      t('extension class'),
      t('CoC on static'), t('CoC on protected'), t('CoC on form'), t('CoC on datasource'),
      t('CoC on form control'), t('CoC on data field'), t('CoC on query'),
      t('CoC on data entity'), t('CoC on table'),
      t('display method'), t('edit method'), t('display static'),
      t('generics'),
      t('SysExtension'), t('ExportMetadata'), t('SysExtensionSingletonAttribute'),
      t('SysExtensionCache'),
      t('attribute class'), t('SysAttribute'),
      t('DictClass'), t('DictMethod'), t('DictTable'), t('DictField'), t('DictEnum'),
      t('DictIndex'), t('DictRelation'), t('DictView'),
      t('SysDictTable'), t('SysDictField'), t('SysDictEnum'), t('SysDictClass'),
      x('TreeNode'),
      t('xSession'), t('xInfo'), t('xUserInfo'), t('xGlobal'), t('xArgs'), t('ClassFactory'),
      t('Box::', /Box::/), t('Debug::', /Debug::/),
      t('Args'), t('parmCaller'), t('parmRecord'), t('parmEnum'), t('parmObject'),
      t('menuItemName'), t('OpenMode'),
    ],
  },
  {
    id: 'I',
    title: 'Tables & the data model',
    terms: [
      t('validateWrite'), t('validateField'), t('validateDelete'),
      t('modifiedField'), t('modifiedFieldValue'), t('initValue'),
      t('find method', /\bfind\(|\bfind method\b/), t('exist method', /\bexist\(|\bexist method\b/),
      t('checkExist'), t('postLoad'),
      t('aosValidateInsert'), t('aosValidateUpdate'), t('aosValidateDelete'), t('aosValidateRead'),
      t('caption'), t('toolTipField'), t('helpField'), t('defaultField'), t('defaultRow'),
      t('initFrom'), t('renamePrimaryKey'), t('canSubmitToWorkflow'),
      t('DataEventHandler'), t('DataEventType'),
      t('ValidateEventArgs'), t('ValidateFieldEventArgs'), t('ModifiedFieldEventArgs'),
      t('DataEventArgs'),
      t('TableGroup'), t('CacheLookup'), t('RecordViewCache'), t('TableType'),
      t('TempDB'), t('InMemory'),
      t('SaveDataPerCompany'), t('SaveDataPerPartition'),
      t('CreatedBy'), t('ModifiedDateTime'), t('RecId'), t('DataAreaId'), t('Partition'),
      t('DeleteAction'), t('Cascade'), t('Restricted'), t('CascadeRestricted'),
      t('Normal relation'), t('ForeignKey'), t('EntityRelationshipType'),
      t('Association'), t('Composition'),
      t('unique index', /\bunique index\b|\bAllowDuplicates\b/),
      t('AlternateKey'), t('ClusteredIndex'), t('ReplacementKey'), t('PrimaryIndex'),
      t('IncludedColumns'),
      t('field group'), t('AutoReport'), t('AutoLookup'), t('AutoIdentification'),
      t('AutoSummary'), t('AutoBrowse'), t('TitleField1'), t('TitleField2'),
      t('ConfigurationKey'), t('CountryRegionCodes'),
      t('Mandatory'), t('AllowEdit'), t('AllowEditOnCreate'), t('IgnoreEDTRelation'),
      t('ExtendedDataType'), t('StringSize'), t('DisplayLength'), t('EnumType'),
      t('IsExtensible'), t('UseEnumValue'),
      t('SupportInheritance'), t('InstanceRelationType'),
      t('map field mapping', /\bMappings?\b|\bmap field mapping\b/),
      t('computed column'), t('SysComputedColumn'), t('view method'),
      t('date effective'), t('ValidTimeStateFieldType'), t('ValidFrom'), t('ValidTo'),
      t('ValidTimeStateAutoQuery'),
      t('OccEnabled'), t('CreateRecIdIndex'),
      x('RecordLevelSecurity'), x('TableCollection'), x('virtual company'),
    ],
  },
  {
    id: 'J',
    title: 'Forms & UI',
    terms: [
      t('FormRun'), t('canClose'), t('closeOk'), t('closeCancel'), t('wait'),
      t('FormDataSource'), t('executeQuery'), t('linkActive'), t('leaveRecord'),
      t('research'), t('refreshEx'), t('positionToRecord'), t('markAsDirty'),
      t('displayOption'), t('FormRowDisplayOption'),
      t('queryBuildDataSource'), t('addRange'), t('FormDataObject'),
      t('FormControl'), t('FormStringControl'), t('FormReferenceGroupControl'),
      t('FormSegmentedEntryControl'), t('FormGridControl'), t('FormTabPageControl'),
      t('FormGroupControl'), t('FormActionPaneControl'), t('FormButtonControl'),
      t('FormComboBoxControl'), t('FormCheckBoxControl'), t('FormDateControl'),
      t('FormRealControl'), t('FormIntControl'), t('FormTimeControl'), t('FormImageControl'),
      t('FormHtmlControl'), t('FormButtonGroupControl'), t('FormMenuButtonControl'),
      t('FormCommandButtonControl'), t('FormDropDialogButtonControl'),
      t('FormFilterPaneControl'), t('FormQuickFilterControl'), t('FormStaticTextControl'),
      t('FormTreeControl'), t('FormListControl'), t('FormWindowControl'),
      t('registerOverrideMethod'),
      t('FormEventHandler'), t('FormEventType'), t('FormDataSourceEventHandler'),
      t('FormDataSourceEventType'), t('FormControlEventHandler'), t('FormControlEventType'),
      t('FormDataFieldEventHandler'), t('FormDataFieldEventType'),
      t('FormControlCancelableSuperEventArgs'), t('FormDataSourceCancelEventArgs'),
      t('SysTableLookup'), t('SysReferenceTableLookup'), t('SysLookupMultiSelectCtrl'),
      t('SysLookupMultiSelectGrid'), t('performFormLookup'), t('lookupReference'),
      t('form pattern'), t('ListPage'), t('DetailsMaster'), t('DetailsTransaction'),
      t('SimpleList'), t('SimpleListDetails'), t('Dialog'), t('Workspace'),
      t('TableOfContents'), t('Wizard'), t('FactBox'), t('Lookup'),
      t('ListPageInteraction'),
      t('menu item'), t('DisplayMenuItem'), t('ActionMenuItem'), t('OutputMenuItem'),
      t('EnumTypeParameter'), t('EnumParameter'), t('NeedsRecord'), t('LinkedPermissionType'),
      t('Tile'), t('KPI'), t('Cue'),
      t('AutoDeclaration'), t('ExtendedStyle'), t('ViewEditMode'),
      t('AllowCreate'), t('AllowDelete'), t('InsertIfEmpty'), t('InsertAtEnd'),
      t('JoinSource'), t('LinkType'), t('InnerJoin'), t('OuterJoin'), t('ExistJoin'), t('Delayed'),
      t('getFirstSelected'),
      t('DialogField'), t('DialogRunbase'), t('dialogSelectCtrl'),
      t('SysOperationUIBuilder'), t('SysOperationAutomaticUIBuilder'),
      t('unbound control'),
      x('extensible control'), x('PowerApp'), x('saved views'), x('personalization'),
      x('SysAttachments'),
    ],
  },
  {
    id: 'K',
    title: 'Data entities & integration',
    terms: [
      t('DataEntityView'), t('data entity'),
      t('mapEntityToDataSource'), t('mapDataSourceToEntity'),
      t('insertEntityDataSource'), t('updateEntityDataSource'), t('persistEntity'),
      t('initializeEntityDataSource'), t('defaultCTQuery'),
      t('DataEntityRuntimeContext'), t('DataEntityDataSourceRuntimeContext'),
      t('validateEntity'), t('EntityKey'),
      t('PublicCollectionName'), t('PublicEntityName'), t('IsPublic'),
      t('DataManagementEnabled'), t('DataManagementStagingTable'), t('staging table'),
      t('EntityCategory'), t('PrimaryCompanyContext'),
      t('unmapped field'), t('virtual field'), t('computed field'), t('EnableSetBased'),
      t('SysODataAction'), t('SysODataActionAttribute'), t('SysODataCollection'),
      t('SysODataFirstOnly'), t('AifCollectionType'),
      t('DataMember'), t('DataContract'), t('custom service'), t('service group'),
      t('OData'), t('$filter', /\$filter/),
      t('DMF'), t('DMFEntityBase'), t('change tracking'), t('ChangeTrackingEnabled'),
      t('composite entity'),
      t('Dual-write'), t('Dataverse'), t('virtual entity'),
      t('business event'), t('BusinessEventsBase'), t('BusinessEventsContract'),
      t('SysMailer'), t('SysMailerMessageBuilder'), t('SysMailerFactory'),
      t('File::SendFileToUser', /File::SendFileToUser/),
      t('CommaTextIo'), t('TextIo'), t('CommaStreamIo'), t('TextStreamIo'),
      t('ExcelPackage'), t('OfficeOpenXml'),
      t('HttpClient'), t('FormJsonSerializer'), t('Newtonsoft'),
      t('XmlDocument'), t('System.Xml', /System\.Xml/),
      t('Regex'), t('Base64'),
      t('MemoryStream'), t('StreamReader'), t('StreamWriter'),
      t('DocuRef'), t('DocuValue'), t('DocumentManagement'), t('attachFile'), t('DocuType'),
      t('Connection'), t('UserConnection'), t('Statement'),
      t('SqlStatementExecutePermission'), t('direct SQL'),
      t('CLRInterop'), t('CLRObject'), t('CLRError'), t('InteropPermission'), t('using alias'),
      x('Azure Blob'), x('Key Vault'), x('recurring integration'),
    ],
  },
  {
    id: 'L',
    title: 'Frameworks',
    terms: [
      t('SysOperation'), t('SysOperationServiceController'), t('SysOperationServiceBase'),
      t('DataContractAttribute'), t('DataMemberAttribute'),
      t('SysOperationLabel'), t('SysOperationHelpText'), t('SysOperationDisplayOrder'),
      t('SysOperationGroup'), t('SysOperationGroupMember'),
      t('SysOperationContractProcessing'), t('SysOperationExecutionMode'),
      t('SysOperationSandbox'), t('SysOperationProgress'), t('AifQueryTypeAttribute'),
      t('SysOperationValidatable'), t('SysOperationInitializable'),
      t('SysOperationDataContractBase'),
      t('pack'), t('unpack'), t('SysPackable'),
      t('RunBase'), t('RunBaseBatch'), t('canGoBatch'), t('canRunInNewSession'),
      t('getFromDialog'), t('putToDialog'), t('initParmDefault'),
      t('BatchHeader'), t('BatchInfo'), t('parmBatchInfo'),
      t('BatchRetryable'), t('isRetryable'), t('runAsync'),
      t('addRuntimeTask'), t('addDependency'),
      t('isRunningInBatch', /isRunningOnBatch|isRunningInBatch/),
      t('batch group'), t('SysRecurrence'),
      t('number sequence'), t('NumberSeq'), t('NumberSeqModule'), t('NumberSeqReference'),
      t('NumberSeqScope'), t('NumberSeqScopeFactory'), t('NumberSeqFormHandler'),
      t('financial dimension'), t('DimensionDefault'), t('DimensionAttributeValueSet'),
      t('DimensionAttributeValueSetStorage'), t('DimensionDefaultingService'),
      t('LedgerDimension'), t('DimensionAttributeValueCombination'), t('DimensionStorage'),
      t('DimensionAttribute'),
      t('LedgerVoucher'), t('SubledgerJournal'), t('SourceDocument'),
      t('workflow'), t('WorkflowWorkItemActionManager'), t('canSubmitToWorkflow'),
      t('WorkflowDocument'), t('WorkflowTypeName'),
      t('WorkflowStartedEventHandler'), t('WorkflowCompletedEventHandler'),
      t('WorkflowCanceledEventHandler'), t('WorkflowElementStartedEventHandler'),
      t('WorkflowElementCompletedEventHandler'), t('WorkflowElementCanceledEventHandler'),
      t('WorkflowElementReturnedEventHandler'), t('WorkflowElementDeniedEventHandler'),
      t('WorkflowWorkItemsCreatedEventHandler'),
      t('WorkflowParticipantProvider'), t('WorkflowHierarchyProvider'), t('WorkflowDueDateProvider'),
      t('feature management'), t('IFeatureMetadata'), t('FeatureStateProvider'),
      t('isFeatureEnabled'), t('flight'),
      t('configuration key'), t('isConfigurationkeyEnabled'), t('license code'),
      t('hasMenuItemAccess'), t('hasTableAccess'), t('hasFieldAccess'), t('checkTableAccess'),
      t('AccessType'), t('AccessRight'),
      t('privilege'), t('duty'), t('role'), t('entry point'),
      t('XDS'), t('security policy'), t('XDSServiceBase'), t('PolicyContext'),
      t('ContextString'), t('ConstrainedTable', /ConstrainedTable|Constrained table/),
      t('DirPartyTable'), t('LogisticsPostalAddress'), t('LogisticsElectronicAddress'),
      t('DirPerson'), t('DirOrganization'), t('DirPartyLocation'),
      t('ExchangeRateHelper'), t('CurrencyExchangeHelper'),
      t('InventDim'), t('InventTrans'), t('InventSum'), t('InventMovement'),
      t('WHSWork'), t('WhsWorkExecuteDisplay'),
      t('ProcessGuideController'), t('ProcessGuideStep'), t('ProcessGuidePageBuilder'),
      t('ProcessGuideNavigationAgent'), t('ProcessGuideDataProcessor'),
      t('PriceDisc'), t('trade agreement'),
      t('SysGlobalObjectCache'), t('SysGlobalCache'), t('SysDataAreaCache'),
      t('SysExtensionAppClassFactory'), t('SysPluginFactory'), t('ExportMetadataAttribute'),
      t('Alerts'), t('EventInbox'),
      t('SystemNotificationsManager'), t('SystemNotificationDataContract'),
      t('ERModelMapping'), t('ERFormatMappingRun'), t('ER custom function'),
      t('DateTimeUtil::applyTimeZoneOffset', /applyTimeZoneOffset/),
      t('Timezone'),
      x('tax framework', /\bTaxTrans\b|\btax framework\b/), x('AssetTable'), x('ProjTable'),
      x('HcmWorker'), x('Retail SDK'), x('ProdTable'), x('BOMTable'), x('ReqTrans'),
      x('Management Reporter'), x('Power BI'),
    ],
  },
  {
    id: 'M',
    title: 'Reporting (SSRS, print management, ER)',
    terms: [
      t('AxReport'), t('SSRS'),
      t('SrsReportDataProviderBase'), t('SrsReportDataProviderPreProcess'),
      t('SrsReportDataProviderPreProcessTempDB'),
      t('SRSReportParameterAttribute'), t('SRSReportQueryAttribute'), t('SRSReportDataSetAttribute'),
      t('SrsReportNameAttribute'),
      t('processReport'), t('getTmp'), t('parmDataContract'), t('parmQuery'),
      t('parmUserConnection'), t('createdTransactionId'),
      t('RDP'), t('RDL'), t('report dataset'),
      t('AutoDesign'), t('PrecisionDesign'), t('Report Designer'),
      t('Tablix'), t('Textbox'), t('page header'), t('page footer'),
      t('Fields!', /Fields!/), t('Parameters!', /Parameters!/), t('Labels!', /Labels!/),
      t('Globals!', /Globals!/), t('ReportItems!', /ReportItems!/),
      t('RDL expression'), t('=Sum(', /=Sum\(/), t('=First(', /=First\(/),
      t('=Format(', /=Format\(/), t('=IIF(', /=IIF\(/), t('Switch(', /\bSwitch\(/),
      t('RowNumber'), t('RunningValue'), t('PageNumber'), t('TotalPages'),
      t('page break'), t('interactive sort'), t('drillthrough'),
      t('Matrix'), t('Chart'), t('conditional formatting'),
      t('logo'), t('CompanyImage'), t('FormLetterReport'),
      t('barcode'), t('BarcodeCode128'), t('BarcodeType'),
      t('SrsReportRunController'), t('parmReportName'), t('parmDialogCaption'),
      t('parmShowDialog'), t('parmArgs'), t('parmLoadFromSysLastValue'),
      t('prePromptModifyContract'), t('preRunModifyContract'), t('startOperation'),
      t('runReport'), t('getReportContract'),
      t('SrsReportRdlDataContract'), t('SrsReportDataContract'), t('SrsReportContractUIBuilder'),
      t('SrsReportDataContractUIBuilder'),
      t('SrsReportRunUtil'), t('SrsReportHelper'), t('SrsReportParameterValidator'),
      t('SrsReportRunPermission'), t('SrsReportRunCache'), t('SrsReportDrillThruUtil'),
      t('SRSPrintDestinationSettings'), t('printMediumType'), t('SRSPrintMediumType'),
      t('SRSReportFileFormat'), t('fileFormat'), t('overwriteFile'),
      t('emailTo'), t('emailSubject'), t('printerName'), t('numberOfCopies'),
      t('SrsReportRunMailer'), t('SrsReportRunPrinter'), t('SRSPrintArchiveContract'),
      t('print archive'),
      t('SrsProxy'), t('renderReportToByteArray'), t('renderReportToStream'),
      t('print management'), t('PrintMgmtDocType'), t('PrintMgmtDocTypeSetup'),
      t('PrintMgmtNode'), t('PrintMgmtReportFormat'), t('PrintMgmtReportFormatPublisher'),
      t('getDefaultReportFormatDelegate'), t('PrintMgmtDelegatesHandler'),
      t('SrsPrintMgmtController'), t('SrsPrintMgmtFormLetterController'), t('runPrintMgmt'),
      t('PrintMgmtHierarchy'), t('PrintMgmtDocumentType'),
      t('report extension'), t('report dataset extension'), t('report custom design'),
      t('report menu redirect'),
      t('AxReportDataSet'), t('AxReportDataSetField'), t('AxReportParameter'),
      t('AxReportDesign'), t('AxReportAutoDesign'), t('AxReportPrecisionDesign'),
      t('AllowBlank'), t('nullable parameter', /\bNullable\b|\bnullable parameter\b/),
      t('MultiValue'), t('hidden parameter', /\bHidden\b|\bhidden parameter\b/),
      t('DefaultParameterGroup'), t('DataMethods'), t('EmbeddedImages'),
      t('AX_RdpPreProcessedId'), t('AX_CompanyName'), t('AX_RenderingCulture'),
      t('AX_ReportContext'), t('AX_UserContext'), t('AX_PartitionKey'),
      t('report in batch'), t('SysLastValue'), t('report localization'),
      t('report security'), t('cross-company report'),
      t('multi dataset', /multi-?dataset/),
      t('report DP test', /processReport test|report DP test/),
      x('sub-report', /\bSubreport\b|\bsub-report\b/),
      x('Document Routing Agent'), x('AxEnumProvider'),
    ],
  },
  {
    id: 'N',
    title: 'Testing & TDD',
    terms: [
      t('SysTestCase'), t('SysTestSuite'), t('SysTestAssert'),
      t('SysTestMethod'), t('SysTestCheckInTest'), t('SysTestNonCheckInTest'),
      t('SysTestInactiveTest'),
      t('SysTestTarget'), t('SysTestCategory'), t('SysTestOwner'), t('SysTestPriority'),
      t('SysTestAreaPath'), t('SysTestGranularity'),
      t('SysTestRow'), t('SysTestRowInactive'),
      t('SysTestCaseDataDependency'), t('SysTestCaseDemoDataDependency'),
      t('SysTestCaseCompanyData'), t('SysTestCaseCountryRegionDependency'),
      t('SysTestCaseAutomaticNumberSequences'),
      t('SysTestCaseNumSeqModuleDependency'), t('SysTestCaseNumSeqTypeDependency'),
      t('SysTestCaseConfigurationKeyDependency'),
      t('SysTestCaseDependsOnReport'), t('SysTestCaseDependsOnBatch'),
      t('SysTestFeatureDependency'), t('SysTestFeatureConfiguration'),
      t('SysTestCaseFlightDependency'),
      t('SysTestCaseUseSingleInstance'), t('SysTestFixture'), t('SysTestKey'),
      t('SysTestSecurity'), t('SysTestTransaction'),
      t('SysTestExtendedInfologEntryCapture'),
      t('SysTestSuiteCompanyIsolateClass'), t('SysTestSuiteCompanyIsolateMethod'),
      t('SysTestSuiteCompIsolateClassWithTts'), t('SysTestSuiteTTS'), t('SysTestSuiteNoCleanup'),
      t('createSuite'),
      t('setUp'), t('tearDown'), t('setUpTestCase'), t('tearDownTestCase'),
      t('assertEquals'), t('assertTrue'), t('assertFalse'), t('assertNotNull'), t('assertNull'),
      t('assertNotEqual'), t('assertRealEquals'), t('assertUTCDateTimeEquals'),
      t('assertSame'), t('assertNotSame'), t('assertEquivalent'), t('assertObjectEquals'),
      t('assertExpectedInfoLogMessage'),
      t('parmExceptionExpected'), t('clearExceptionExpected'),
      t('assertExpectedException'),
      t('fail'),
      t('SysTestListenerXML'), t('SysTestConsole'),
      t('/unattended', /\/unattended/), t('/xml:', /\/xml:/), t('/test:', /\/test:/),
      t('Test Explorer'), t('TestEssentials'),
      t('SysTestBatchScheduler'), t('SysTestBatchTask'),
      t('ATL'), t('Acceptance Test Library'),
      t('AtlDataRootNode'), t('AtlCommand'), t('AtlCreator', /AtlCreator/),
      t('AtlEntity', /AtlEntity/), t('AtlQuery', /AtlQuery/), t('AtlSpec', /AtlSpec/),
      t('AtlFoundation'), t('ATLApplicationSuite'), t('AtlSampleTests'),
      t('test data'), t('test isolation'), t('transaction rollback'), t('company isolation'),
      t('FormAdaptor'), t('form test'),
      t('mock'), t('stub'), t('test double'), t('dependency injection'), t('seam'),
      t('Arrange'), t('Act'), t('Assert'),
      t('red-first', /red-?first/), t('red-green', /red-?green/), t('TDD'), t('test-driven'),
      t('refactor'), t('unit test'), t('integration test'),
      t('test naming'), t('negative test'), t('expected exception'),
      t('data-driven test'), t('parameterized test'),
      t('test of validateWrite', /test of validateWrite|validateWrite test/),
      t('test of CoC', /test of CoC|CoC test/),
      t('test of event handler', /test of event handler|event handler test/),
      t('test of SysOperation service', /test of SysOperation|service test/),
      t('test of report DP', /test of report DP|report DP test/),
      t('test of data entity', /test of data entity|entity test/),
      t('UT01'), t('DAT company'),
      x('RSAT'), x('Task Recorder'), x('code coverage'), x('performance test'),
    ],
  },
  {
    id: 'O',
    title: 'Best practice & lifecycle',
    terms: [
      t('best practice'), t('xppbp'), t('SuppressBPWarning'), t('BPErrorLabelIsText'),
      t('BPXmlDoc'), t('naming convention'), t('model prefix'),
      t('label'), t('@SYS', /@SYS/), t('@Label:', /@Label:/), t('label file'),
      t('literalStr'), t('SysLabel'), t('labelId2String'),
      t('translation'), t('localization'),
      t('deprecated'), t('obsolete'), t('migration'), t('overlayering'), t('extension model'),
      t('Descriptor'), t('ModelReferences'),
      t('xppc'), t('DB sync', /DB sync|database synchron/i),
      t('full build'), t('incremental build'),
      t('cross-reference'), t('find references'),
      t('CodeAccessPermission'), t('assert permission', /\bassert\(\)|assert permission/),
      t('revertAssert'), t('FileIOPermission'), t('InteropPermission'), t('ExecutePermission'),
      t('RunAsPermission'),
      t('developer documentation'), t('help text'),
      t('camelCase'), t('PascalCase'),
      t('set-based operation'), t('index design'), t('covering index'),
      t('deadlock'), t('lock escalation'), t('long transaction'),
      t('trace'), t('telemetry'),
      x('LCS'), x('Azure DevOps'), x('deployable package'), x('One Version'),
      x('SonarQube'), x('cyclomatic'), x('TFVC'),
    ],
  },
];

/** Total term count, so a caller can report the map's size without walking it. */
export const TERM_COUNT = AXES.reduce((n, a) => n + a.terms.length, 0);
